### ISSUE TITLE
Exception encountered due to whitespace in link value to be dereferenced

### ISSUE THREAD

**Issue by Manj75** [archi-contribs/snow-import-plugin#9]
With the default setting to dereference links (`&sysparm_exclude_reference_link=false`) the value returned and then being dereferenced contains whitespaces and causes the exception from what I can tell.

Value here is **Technical Services South**

`2019-10-01 12:12:15 TRACE 1240:MyImporter           -       Following reference link to URL https://nextdev.service-now.com/api/now/table/sys_user_group/Technical Services South
2019-10-01 12:12:15 ERROR 1256:MyImporter           - Failed to get URL from ServiceNow.
org.archicontribs.servicenow.MyException: Error reported by ServiceNow website : code 400
	at org.archicontribs.servicenow.MyConnection.get(MyConnection.java:66)
	at org.archicontribs.servicenow.MyImporter.getJsonField(MyImporter.java:1244)
	at org.archicontribs.servicenow.MyImporter.getJsonField(MyImporter.java:1191)
	at org.archicontribs.servicenow.MyImporter.expand(MyImporter.java:1438)
	at org.archicontribs.servicenow.MyImporter.doImport(MyImporter.java:588)
	at com.archimatetool.editor.actions.ImportIntoModelAction.run(ImportIntoModelAction.java:37)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at com.archimatetool.editor.Application.start(Application.java:84)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)`

**Comment by herve91** [comment]
noted ... will fix it.

Thanks
